# Generated by Django 5.0.4 on 2024-04-07 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankingapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='balance',
            field=models.IntegerField(null=True),
        ),
    ]
