# Generated by Django 5.0.4 on 2024-04-11 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankingapp', '0004_alter_deposits_account_alter_deposits_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposits',
            name='message',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
