# Generated by Django 5.0.4 on 2024-04-13 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankingapp', '0005_deposits_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_amount', models.IntegerField()),
                ('annual_income', models.IntegerField()),
                ('loan_type', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=300)),
                ('dob', models.DateField()),
                ('marital_status', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=2000)),
                ('address_year', models.CharField(max_length=100)),
                ('employer', models.CharField(max_length=200)),
                ('occupation', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=100)),
                ('income', models.IntegerField()),
                ('mortgage', models.IntegerField()),
                ('bank', models.CharField(max_length=2000)),
                ('accountNum', models.IntegerField()),
            ],
        ),
    ]
