# Generated by Django 5.0.4 on 2024-04-14 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankingapp', '0007_loanapplication_aadhar_loanapplication_pan'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='comments',
            field=models.CharField(max_length=3000, null=True),
        ),
    ]
