# Generated by Django 5.0.4 on 2024-04-17 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankingapp', '0013_loanapplication_login_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
