# Generated by Django 5.0.4 on 2024-04-22 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankingapp', '0016_complaints_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='dateTime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
